// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: travel.proto

package server

import (
	"context"

	"github.com/wwwzy/ZeroMicroServices/app/travel/cmd/rpc/internal/logic"
	"github.com/wwwzy/ZeroMicroServices/app/travel/cmd/rpc/internal/svc"
	"github.com/wwwzy/ZeroMicroServices/app/travel/cmd/rpc/pb"
)

type TravelServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTravelServer
}

func NewTravelServer(svcCtx *svc.ServiceContext) *TravelServer {
	return &TravelServer{
		svcCtx: svcCtx,
	}
}

// 获取民宿详细信息
func (s *TravelServer) HomestayDetail(ctx context.Context, in *pb.HomestayDetailReq) (*pb.HomestayDetailResp, error) {
	l := logic.NewHomestayDetailLogic(ctx, s.svcCtx)
	return l.HomestayDetail(in)
}
