// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据
type HomestayOrder struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn                  string                 `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	UserId              int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	HomestayId          int64                  `protobuf:"varint,4,opt,name=homestayId,proto3" json:"homestayId,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle            string                 `protobuf:"bytes,6,opt,name=subTitle,proto3" json:"subTitle,omitempty"`
	Cover               string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Info                string                 `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	PeopleNum           int64                  `protobuf:"varint,9,opt,name=peopleNum,proto3" json:"peopleNum,omitempty"`
	RowType             int64                  `protobuf:"varint,10,opt,name=rowType,proto3" json:"rowType,omitempty"`
	FoodInfo            string                 `protobuf:"bytes,11,opt,name=foodInfo,proto3" json:"foodInfo,omitempty"`
	FoodPrice           int64                  `protobuf:"varint,12,opt,name=foodPrice,proto3" json:"foodPrice,omitempty"`
	HomestayPrice       int64                  `protobuf:"varint,13,opt,name=homestayPrice,proto3" json:"homestayPrice,omitempty"`
	MarketHomestayPrice int64                  `protobuf:"varint,14,opt,name=marketHomestayPrice,proto3" json:"marketHomestayPrice,omitempty"`
	HomestayBusinessId  int64                  `protobuf:"varint,15,opt,name=homestayBusinessId,proto3" json:"homestayBusinessId,omitempty"`
	HomestayUserId      int64                  `protobuf:"varint,16,opt,name=homestayUserId,proto3" json:"homestayUserId,omitempty"`
	LiveStartDate       int64                  `protobuf:"varint,17,opt,name=liveStartDate,proto3" json:"liveStartDate,omitempty"`
	LiveEndDate         int64                  `protobuf:"varint,18,opt,name=liveEndDate,proto3" json:"liveEndDate,omitempty"`
	LivePeopleNum       int64                  `protobuf:"varint,19,opt,name=livePeopleNum,proto3" json:"livePeopleNum,omitempty"`
	TradeState          int64                  `protobuf:"varint,20,opt,name=tradeState,proto3" json:"tradeState,omitempty"`
	TradeCode           string                 `protobuf:"bytes,21,opt,name=tradeCode,proto3" json:"tradeCode,omitempty"`
	Remark              string                 `protobuf:"bytes,22,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderTotalPrice     int64                  `protobuf:"varint,23,opt,name=orderTotalPrice,proto3" json:"orderTotalPrice,omitempty"`
	FoodTotalPrice      int64                  `protobuf:"varint,24,opt,name=foodTotalPrice,proto3" json:"foodTotalPrice,omitempty"`
	HomestayTotalPrice  int64                  `protobuf:"varint,25,opt,name=homestayTotalPrice,proto3" json:"homestayTotalPrice,omitempty"`
	CreateTime          int64                  `protobuf:"varint,26,opt,name=createTime,proto3" json:"createTime,omitempty"`
	NeedFood            int64                  `protobuf:"varint,27,opt,name=needFood,proto3" json:"needFood,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HomestayOrder) Reset() {
	*x = HomestayOrder{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrder) ProtoMessage() {}

func (x *HomestayOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrder.ProtoReflect.Descriptor instead.
func (*HomestayOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *HomestayOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomestayOrder) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *HomestayOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HomestayOrder) GetHomestayId() int64 {
	if x != nil {
		return x.HomestayId
	}
	return 0
}

func (x *HomestayOrder) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomestayOrder) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *HomestayOrder) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *HomestayOrder) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HomestayOrder) GetPeopleNum() int64 {
	if x != nil {
		return x.PeopleNum
	}
	return 0
}

func (x *HomestayOrder) GetRowType() int64 {
	if x != nil {
		return x.RowType
	}
	return 0
}

func (x *HomestayOrder) GetFoodInfo() string {
	if x != nil {
		return x.FoodInfo
	}
	return ""
}

func (x *HomestayOrder) GetFoodPrice() int64 {
	if x != nil {
		return x.FoodPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayPrice() int64 {
	if x != nil {
		return x.HomestayPrice
	}
	return 0
}

func (x *HomestayOrder) GetMarketHomestayPrice() int64 {
	if x != nil {
		return x.MarketHomestayPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayBusinessId() int64 {
	if x != nil {
		return x.HomestayBusinessId
	}
	return 0
}

func (x *HomestayOrder) GetHomestayUserId() int64 {
	if x != nil {
		return x.HomestayUserId
	}
	return 0
}

func (x *HomestayOrder) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *HomestayOrder) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *HomestayOrder) GetLivePeopleNum() int64 {
	if x != nil {
		return x.LivePeopleNum
	}
	return 0
}

func (x *HomestayOrder) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

func (x *HomestayOrder) GetTradeCode() string {
	if x != nil {
		return x.TradeCode
	}
	return ""
}

func (x *HomestayOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *HomestayOrder) GetOrderTotalPrice() int64 {
	if x != nil {
		return x.OrderTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetFoodTotalPrice() int64 {
	if x != nil {
		return x.FoodTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayTotalPrice() int64 {
	if x != nil {
		return x.HomestayTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *HomestayOrder) GetNeedFood() int64 {
	if x != nil {
		return x.NeedFood
	}
	return 0
}

// 请求回应
type CreateHomestayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomestayId    int64                  `protobuf:"varint,1,opt,name=homestayId,proto3" json:"homestayId,omitempty"`
	IsFood        bool                   `protobuf:"varint,2,opt,name=isFood,proto3" json:"isFood,omitempty"`
	LiveStartTime int64                  `protobuf:"varint,3,opt,name=liveStartTime,proto3" json:"liveStartTime,omitempty"`
	LiveEndTime   int64                  `protobuf:"varint,4,opt,name=liveEndTime,proto3" json:"liveEndTime,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	LivePeopleNum int64                  `protobuf:"varint,6,opt,name=livePeopleNum,proto3" json:"livePeopleNum,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomestayOrderReq) Reset() {
	*x = CreateHomestayOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomestayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomestayOrderReq) ProtoMessage() {}

func (x *CreateHomestayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomestayOrderReq.ProtoReflect.Descriptor instead.
func (*CreateHomestayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHomestayOrderReq) GetHomestayId() int64 {
	if x != nil {
		return x.HomestayId
	}
	return 0
}

func (x *CreateHomestayOrderReq) GetIsFood() bool {
	if x != nil {
		return x.IsFood
	}
	return false
}

func (x *CreateHomestayOrderReq) GetLiveStartTime() int64 {
	if x != nil {
		return x.LiveStartTime
	}
	return 0
}

func (x *CreateHomestayOrderReq) GetLiveEndTime() int64 {
	if x != nil {
		return x.LiveEndTime
	}
	return 0
}

func (x *CreateHomestayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateHomestayOrderReq) GetLivePeopleNum() int64 {
	if x != nil {
		return x.LivePeopleNum
	}
	return 0
}

func (x *CreateHomestayOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateHomestayOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomestayOrderResp) Reset() {
	*x = CreateHomestayOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomestayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomestayOrderResp) ProtoMessage() {}

func (x *CreateHomestayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomestayOrderResp.ProtoReflect.Descriptor instead.
func (*CreateHomestayOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHomestayOrderResp) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type HomestayOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayOrderDetailReq) Reset() {
	*x = HomestayOrderDetailReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrderDetailReq) ProtoMessage() {}

func (x *HomestayOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrderDetailReq.ProtoReflect.Descriptor instead.
func (*HomestayOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *HomestayOrderDetailReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type HomestayOrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomestayOrder *HomestayOrder         `protobuf:"bytes,1,opt,name=homestayOrder,proto3" json:"homestayOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayOrderDetailResp) Reset() {
	*x = HomestayOrderDetailResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrderDetailResp) ProtoMessage() {}

func (x *HomestayOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrderDetailResp.ProtoReflect.Descriptor instead.
func (*HomestayOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *HomestayOrderDetailResp) GetHomestayOrder() *HomestayOrder {
	if x != nil {
		return x.HomestayOrder
	}
	return nil
}

type UpdateHomestayOrderTradeStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	TradeState    int64                  `protobuf:"varint,2,opt,name=tradeState,proto3" json:"tradeState,omitempty"` //-1: 已取消 0:待支付 1:未使用 2:已使用  3:已过关闭
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHomestayOrderTradeStateReq) Reset() {
	*x = UpdateHomestayOrderTradeStateReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomestayOrderTradeStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomestayOrderTradeStateReq) ProtoMessage() {}

func (x *UpdateHomestayOrderTradeStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomestayOrderTradeStateReq.ProtoReflect.Descriptor instead.
func (*UpdateHomestayOrderTradeStateReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHomestayOrderTradeStateReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateReq) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

type UpdateHomestayOrderTradeStateResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Sn              string                 `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn,omitempty"`
	TradeCode       string                 `protobuf:"bytes,4,opt,name=tradeCode,proto3" json:"tradeCode,omitempty"`
	LiveStartDate   int64                  `protobuf:"varint,5,opt,name=liveStartDate,proto3" json:"liveStartDate,omitempty"`
	LiveEndDate     int64                  `protobuf:"varint,6,opt,name=liveEndDate,proto3" json:"liveEndDate,omitempty"`
	OrderTotalPrice int64                  `protobuf:"varint,7,opt,name=orderTotalPrice,proto3" json:"orderTotalPrice,omitempty"`
	Title           string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateHomestayOrderTradeStateResp) Reset() {
	*x = UpdateHomestayOrderTradeStateResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomestayOrderTradeStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomestayOrderTradeStateResp) ProtoMessage() {}

func (x *UpdateHomestayOrderTradeStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomestayOrderTradeStateResp.ProtoReflect.Descriptor instead.
func (*UpdateHomestayOrderTradeStateResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHomestayOrderTradeStateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResp) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateResp) GetTradeCode() string {
	if x != nil {
		return x.TradeCode
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateResp) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResp) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResp) GetOrderTotalPrice() int64 {
	if x != nil {
		return x.OrderTotalPrice
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UserHomestayOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TraderState   int64                  `protobuf:"varint,4,opt,name=traderState,proto3" json:"traderState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHomestayOrderListReq) Reset() {
	*x = UserHomestayOrderListReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomestayOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomestayOrderListReq) ProtoMessage() {}

func (x *UserHomestayOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomestayOrderListReq.ProtoReflect.Descriptor instead.
func (*UserHomestayOrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *UserHomestayOrderListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *UserHomestayOrderListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserHomestayOrderListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserHomestayOrderListReq) GetTraderState() int64 {
	if x != nil {
		return x.TraderState
	}
	return 0
}

type UserHomestayOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HomestayOrder       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHomestayOrderListResp) Reset() {
	*x = UserHomestayOrderListResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomestayOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomestayOrderListResp) ProtoMessage() {}

func (x *UserHomestayOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomestayOrderListResp.ProtoReflect.Descriptor instead.
func (*UserHomestayOrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UserHomestayOrderListResp) GetList() []*HomestayOrder {
	if x != nil {
		return x.List
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x02pb\"\xe7\x06\n" +
	"\rHomestayOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"homestayId\x18\x04 \x01(\x03R\n" +
	"homestayId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubTitle\x18\x06 \x01(\tR\bsubTitle\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x12\n" +
	"\x04info\x18\b \x01(\tR\x04info\x12\x1c\n" +
	"\tpeopleNum\x18\t \x01(\x03R\tpeopleNum\x12\x18\n" +
	"\arowType\x18\n" +
	" \x01(\x03R\arowType\x12\x1a\n" +
	"\bfoodInfo\x18\v \x01(\tR\bfoodInfo\x12\x1c\n" +
	"\tfoodPrice\x18\f \x01(\x03R\tfoodPrice\x12$\n" +
	"\rhomestayPrice\x18\r \x01(\x03R\rhomestayPrice\x120\n" +
	"\x13marketHomestayPrice\x18\x0e \x01(\x03R\x13marketHomestayPrice\x12.\n" +
	"\x12homestayBusinessId\x18\x0f \x01(\x03R\x12homestayBusinessId\x12&\n" +
	"\x0ehomestayUserId\x18\x10 \x01(\x03R\x0ehomestayUserId\x12$\n" +
	"\rliveStartDate\x18\x11 \x01(\x03R\rliveStartDate\x12 \n" +
	"\vliveEndDate\x18\x12 \x01(\x03R\vliveEndDate\x12$\n" +
	"\rlivePeopleNum\x18\x13 \x01(\x03R\rlivePeopleNum\x12\x1e\n" +
	"\n" +
	"tradeState\x18\x14 \x01(\x03R\n" +
	"tradeState\x12\x1c\n" +
	"\ttradeCode\x18\x15 \x01(\tR\ttradeCode\x12\x16\n" +
	"\x06remark\x18\x16 \x01(\tR\x06remark\x12(\n" +
	"\x0forderTotalPrice\x18\x17 \x01(\x03R\x0forderTotalPrice\x12&\n" +
	"\x0efoodTotalPrice\x18\x18 \x01(\x03R\x0efoodTotalPrice\x12.\n" +
	"\x12homestayTotalPrice\x18\x19 \x01(\x03R\x12homestayTotalPrice\x12\x1e\n" +
	"\n" +
	"createTime\x18\x1a \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bneedFood\x18\x1b \x01(\x03R\bneedFood\"\xee\x01\n" +
	"\x16CreateHomestayOrderReq\x12\x1e\n" +
	"\n" +
	"homestayId\x18\x01 \x01(\x03R\n" +
	"homestayId\x12\x16\n" +
	"\x06isFood\x18\x02 \x01(\bR\x06isFood\x12$\n" +
	"\rliveStartTime\x18\x03 \x01(\x03R\rliveStartTime\x12 \n" +
	"\vliveEndTime\x18\x04 \x01(\x03R\vliveEndTime\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\x03R\x06userId\x12$\n" +
	"\rlivePeopleNum\x18\x06 \x01(\x03R\rlivePeopleNum\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\")\n" +
	"\x17CreateHomestayOrderResp\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\"(\n" +
	"\x16HomestayOrderDetailReq\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\"R\n" +
	"\x17HomestayOrderDetailResp\x127\n" +
	"\rhomestayOrder\x18\x01 \x01(\v2\x11.pb.HomestayOrderR\rhomestayOrder\"R\n" +
	" UpdateHomestayOrderTradeStateReq\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x1e\n" +
	"\n" +
	"tradeState\x18\x02 \x01(\x03R\n" +
	"tradeState\"\x81\x02\n" +
	"!UpdateHomestayOrderTradeStateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\x12\x1c\n" +
	"\ttradeCode\x18\x04 \x01(\tR\ttradeCode\x12$\n" +
	"\rliveStartDate\x18\x05 \x01(\x03R\rliveStartDate\x12 \n" +
	"\vliveEndDate\x18\x06 \x01(\x03R\vliveEndDate\x12(\n" +
	"\x0forderTotalPrice\x18\a \x01(\x03R\x0forderTotalPrice\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\"\x88\x01\n" +
	"\x18UserHomestayOrderListReq\x12\x16\n" +
	"\x06lastId\x18\x01 \x01(\x03R\x06lastId\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12 \n" +
	"\vtraderState\x18\x04 \x01(\x03R\vtraderState\"B\n" +
	"\x19UserHomestayOrderListResp\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.pb.HomestayOrderR\x04list2\xeb\x02\n" +
	"\x05order\x12N\n" +
	"\x13createHomestayOrder\x12\x1a.pb.CreateHomestayOrderReq\x1a\x1b.pb.CreateHomestayOrderResp\x12N\n" +
	"\x13homestayOrderDetail\x12\x1a.pb.HomestayOrderDetailReq\x1a\x1b.pb.HomestayOrderDetailResp\x12l\n" +
	"\x1dupdateHomestayOrderTradeState\x12$.pb.UpdateHomestayOrderTradeStateReq\x1a%.pb.UpdateHomestayOrderTradeStateResp\x12T\n" +
	"\x15userHomestayOrderList\x12\x1c.pb.UserHomestayOrderListReq\x1a\x1d.pb.UserHomestayOrderListRespB\x06Z\x04./pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_proto_goTypes = []any{
	(*HomestayOrder)(nil),                     // 0: pb.HomestayOrder
	(*CreateHomestayOrderReq)(nil),            // 1: pb.CreateHomestayOrderReq
	(*CreateHomestayOrderResp)(nil),           // 2: pb.CreateHomestayOrderResp
	(*HomestayOrderDetailReq)(nil),            // 3: pb.HomestayOrderDetailReq
	(*HomestayOrderDetailResp)(nil),           // 4: pb.HomestayOrderDetailResp
	(*UpdateHomestayOrderTradeStateReq)(nil),  // 5: pb.UpdateHomestayOrderTradeStateReq
	(*UpdateHomestayOrderTradeStateResp)(nil), // 6: pb.UpdateHomestayOrderTradeStateResp
	(*UserHomestayOrderListReq)(nil),          // 7: pb.UserHomestayOrderListReq
	(*UserHomestayOrderListResp)(nil),         // 8: pb.UserHomestayOrderListResp
}
var file_order_proto_depIdxs = []int32{
	0, // 0: pb.HomestayOrderDetailResp.homestayOrder:type_name -> pb.HomestayOrder
	0, // 1: pb.UserHomestayOrderListResp.list:type_name -> pb.HomestayOrder
	1, // 2: pb.order.createHomestayOrder:input_type -> pb.CreateHomestayOrderReq
	3, // 3: pb.order.homestayOrderDetail:input_type -> pb.HomestayOrderDetailReq
	5, // 4: pb.order.updateHomestayOrderTradeState:input_type -> pb.UpdateHomestayOrderTradeStateReq
	7, // 5: pb.order.userHomestayOrderList:input_type -> pb.UserHomestayOrderListReq
	2, // 6: pb.order.createHomestayOrder:output_type -> pb.CreateHomestayOrderResp
	4, // 7: pb.order.homestayOrderDetail:output_type -> pb.HomestayOrderDetailResp
	6, // 8: pb.order.updateHomestayOrderTradeState:output_type -> pb.UpdateHomestayOrderTradeStateResp
	8, // 9: pb.order.userHomestayOrderList:output_type -> pb.UserHomestayOrderListResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
